spring:
  application:
    name: slack-service
  config:
    import:
      - file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml


server:
  port: ${SLACK_SERVER_PORT}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}  # Eureka 서버 주소


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model:
    name: ${GEMINI_MODEL_NAME}