server:
  port: ${HUB_SERVER_PORT}

spring:
  application:
    name: hub-service
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

naver:
  api:
    client-id: ${NAVER_MAP_API_KEY_ID}
    client-secret: ${NAVER_MAP_API_KEY}