### 회원가입

### 로그인
POST http://localhost:19091/api/auth/signIn
Content-Type: application/json

{
  "userName": "hubmng",
  "userPassword": "Test@1234"
}

### 주문 생성
POST http://localhost:19091/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIzOWVlMGZiZS1kOWZlLTQyM2UtODYxNC05NTRjM2QzZmZkMzciLCJ1c2VyTmFtZSI6Imh1Ym1uZyIsInJvbGUiOiJIVUJfTUFOQUdFUiIsImV4cCI6MTc0MjgxODI3MywiaWF0IjoxNzQyODE3NjczfQ.NXGL4tSczNo-l72qzkL47UrrnnGnhadmxD33nUQSscQ

{
  "orderSupplyCompanyId": "6fa459ea-ee8a-3ca4-894e-db77e160355e",
  "orderReceiveCompanyId": "ee789c62-5c1d-44d4-9dc1-3a4f58e63bb5",
  "orderProductId": "d4e5f6a7-b8c9-4012-def0-456789abcdef",
  "orderProductQuantity": 20,
  "orderDeadline": "2025-03-23T12:00:00.000Z",
  "orderRequirement": "포장 꼼꼼히 해주세요."
}