### 주문 생성
POST http://localhost:19091/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJ1c2VyTmFtZSI6Im1hc3RlciIsInJvbGUiOiJNQVNURVIiLCJleHAiOjE3NDg4ODUwNzQsImlhdCI6MTc0Mjg4NTA3NH0.m8B9HRAn4u-zQKMlwnb7wpQ_ZtrB7b4nbpHoKWhI8I8
Content-Type: application/json

{
  "orderSupplyCompanyId": "20000000-0000-0000-0000-000000000001",
  "orderReceiveCompanyId": "20000000-0000-0000-0000-000000000002",
  "orderProductId": "30000000-0000-0000-0000-000000000001",
  "orderProductQuantity": 40,
  "orderDeadline": "2025-03-23T12:00:00.000Z",
  "orderRequirement": "포장 꼼꼼히 해주세요."
}

### 주문 조회
GET http://localhost:19096/api/orders/3bbb24a9-ff02-4b80-94f2-551e34bcb458

### 주문 리스트 조회
GET http://localhost:19096/api/orders?keyword=&page=&size=&sortDirection=&sortBy=
X-User-Role: COMPANY_MANAGER
X-User-Id: 423e4567-e89b-12d3-a456-426614174003

### 주문 수정
PATCH http://localhost:19096/api/orders/3bbb24a9-ff02-4b80-94f2-551e34bcb458
Content-Type: application/json
X-User-Role: MASTER
X-User-Id: 423e4567-e89b-12d3-a456-426614174003

{
  "orderRequirement": "포장 뭐 대~~~~충 해주세요."
}

### 주문 삭제
DELETE http://localhost:19096/api/orders/3bbb24a9-ff02-4b80-94f2-551e34bcb458
X-User-Role: MASTER
X-User-Id: 423e4567-e89b-12d3-a456-426614174003

### 업체담당자ID로 업체ID 조회
GET http://localhost:19094/api/companies/company-manager/323e4567-e89b-12d3-a456-426614174002

### 허브ID로 업체ID 목록 조회

### 업체ID로 허브ID 조회
GET http://localhost:19094/api/companies/hub/6fa459ea-ee8a-3ca4-894e-db77e160355e