## local 환경
spring:
  config.activate.on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: delivery
  sql:
    init:
      mode: always
      # 나중에 더미데이터 넣고 시작
      # data-locations: classpath:db/data.sql