spring:
  application:
    name: user-service
  config:
    import:
      - file:.env[.properties]
      - classpath:./properties/datasource.yml
      - classpath:./properties/jpa.yml

service:
  jwt:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
    secret-key: ${JWT_SECRET_KEY}


server:
  port: ${USER_SEVER_PORT}  # 유저 서비스 포트

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}  # Eureka 서버 주소