spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: order
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    import: optional:file:.env[.properties]
server:
  port: ${ORDER_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

logging:
  level:
    com.fn.eureka.client.orderservice.infrastructure.CompanyServiceClient: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG