spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: product
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    import: optional:file:.env[.properties]
server:
  port: ${PRODUCT_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
#  instance:
#    prefer-ip-address: true
#    instance-id: product-service:${PRODUCT_SERVER_PORT}
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#  discovery:
#    enabled: true

#logging:
#  level:
#    root: INFO
#    org.springframework.cloud.openfeign: DEBUG
#    com.fn.eureka.client.product.infrastructure.CompanyServiceClient: DEBUG