spring:
  application:
    name: delivery-service
  config:
    import:
    - file:.env[.properties]
    - classpath:./properties/key.yml
    - classpath:./properties/datasource.yml
    - classpath:./properties/jpa.yml
  profiles:
    group:
      local: local, key
    active: ${ACTIVE_VAL}

server:
  port: ${DELIVERY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}  # Eureka 서버 URL