spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: slack

  sql:
    init:
      mode: always
